### ISSUE TITLE
Parameter 'event' implicitly has an 'any' type

### ISSUE THREAD

**Issue by voohoo** [ng2-ui/ng2-auto-complete#15]
My project's typescript transpilation fails due to the following error:

> node_modules/ng2-auto-complete/dist/auto-complete.directive.ts(92,31): error TS7006: Parameter 'event' implicitly has an 'any' type.

Can you please remedy this by explicitly declaring a type?  `(event?: any)`

**Comment by allenhwkim** [comment]
Thanks for reporting this.
However, if you are using .js like the following, I don't know why this is happening
```

map['ng2-auto-complete'] = 'node_modules/ng2-auto-complete/dist';
packages['ng2-auto-complete'] = { main: 'index.js', defaultExtension: 'js' }
```

**Comment by Kimpossibru** [comment]
Made a pull request for this today which has been merged, I would guess this topic can be closed :)
And it probably happens because if you run tsc you are also compiling everything in the node_modules folder unless you do something about it. You should probably ignore the node_modules folder if you are using js files.

**Comment by allenhwkim** [comment]
thanks @Kimpossibru
