### ISSUE TITLE
Bind source to Observable

### ISSUE THREAD

**Issue by andregs** [ng2-ui/ng2-auto-complete#19]
Hi, guys.

Is it possible to bind the `source` property to an `Observable`? It seems it only supports `array` or `string`.

My use case: I have a method in a service that does some async processing and then returns an Observable array. I want to bind the auto-complete to this method.

Thanks!

**Comment by allenhwkim** [comment]
I agree with you. We should accept a `Observable` or `Promise` as source. Will try `Observable` first.

**Comment by Dill1** [comment]
Agreed, thank you. I was going to request accepting an error handling function when binding to a URL so that the error isn't ignored (line 174 autocomplete.component.ts). My use case is that the URL is an internal restful service that requires authentication, and I need to handle 401. But binding to an Observable would allow me to call the service the way I normally do rather than using the URL directly, and to handle the response.

**Comment by allenhwkim** [comment]
This has been released with 0.6.4.

**Comment by boban984** [comment]
@andregs Is the issue resolved now? if so we need to close the issue

**Comment by andregs** [comment]
Thank you!
