### ISSUE TITLE
Dropdown is behind another auto-complete when we place a dropdown belowthe other

### ISSUE THREAD

**Issue by ffcvr2** [ng2-ui/ng2-auto-complete#54]
I face a problem when placing a dropdown below the other. 
![untitled](https://cloud.githubusercontent.com/assets/17157695/20205227/ad6b4d00-a809-11e6-9fe7-7a5dc6374f22.png)

Do you have any suggestions on this problem?

**Comment by jenscl** [comment]
I've this problem too. There are three auto-complete boxes below each other. The problem occurs when leaving the second box (without selecting a value) by clicking on the first box. The auto-complete dropdown correctly shifts to the first one, but the input field of the second box appears on top of the dropdown list.
![snip](https://cloud.githubusercontent.com/assets/18397964/20490978/1f3c29f0-b010-11e6-9ae4-69c457714354.PNG)

**Comment by ffcvr2** [comment]
It seems I didnot describe clearly. My case is the same as jenscl

**Comment by aberonni** [comment]
I'm having the same issue. Just for clarity I've created a [fork of the example plunkr](http://embed.plnkr.co/bGFvgHfG3qrG5WDout8r/) in order to reproduce the problem. The only difference with the example plunkr is that I have added more options to the first dropdown.

Steps to reproduce:

- Click on second dropdown
- Click on first dropdown
- Observe second dropdown

I'm trying to see if I can understand what is happening and eventually submit a PR.

**Comment by allenhwkim** [comment]
Thank you for reporting this issue and helps to understand it.
The issue is that the input box of the second dropdown is still visible with high zIndex.
![image](https://cloud.githubusercontent.com/assets/1437734/20762853/d5013ec4-b6f5-11e6-8c0a-1ba1f5f2faf7.png)
I will see what I can do about it.
Meanwhile, any help would be highly appreciated.
